apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: default
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld-http
          image: strm/helloworld-http:latest
        ports:
        - containerPort: 80
        env:
        - name: FOO
          value: "BAR"

